project:
  type: website
  output-dir: docs

website:
  title: "Data Governance"
  navbar:
    left:
      - href: pages/cmp_overview.qmd
        text: Program Overview
      - pages/quality_control.qmd
      - pages/temperature.qmd
      - text: "Dissolved Oxygen"
        menu:
          - pages/do_overview.qmd
format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: source
execute: 
  freeze: auto
  
bibliography: references/cmp_threshold_references.bib
