project:
  type: website
  output-dir: docs

website:
  title: "Data Governance"
  navbar:
    left:
      - href: pages/cmp_overview.qmd
        text: Program Overview
      - text: "Quality Control"
        menu:
          - pages/qc_overview.qmd
          - pages/qc_tests.qmd
      - text: "Dissolved Oxygen"
        menu:
          - pages/do_overview.qmd
          - pages/do_measurements.qmd
      - text: "Temperature"
        menu:
          - pages/temp_overview.qmd
          - pages/temp_measurements.qmd
          - pages/temp_thresholds.qmd
format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: source
execute: 
  freeze: auto
  
bibliography: references/cmp_threshold_references.bib
